name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t yourusername/your-image-name:latest .

      - name: Push the Docker image
        run: |
          docker push yourusername/your-image-name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into GCP VM and deploy
        run: |
          ssh -o StrictHostKeyChecking=no user@your-vm-ip <<EOF
            docker pull yourusername/your-image-name:latest
            docker stop old-container
            docker rm old-container
            docker run -d -p 80:80 --name new-container yourusername/your-image-name:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
