name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t anchalshivank99/mt-auth-service:latest .

      - name: Push the Docker image
        run: |
          docker push anchalshivank99/mt-auth-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into GCP VM and deploy
        run: |
          ssh -o StrictHostKeyChecking=no mt-backend@34.133.145.146 <<EOF
            docker pull anchalshivank99/mt-auth-service:latest
            docker stop auth-service
            docker rm auth-service
            docker run -d -p 8080:8080 --name auth-service anchalshivank99/mt-auth-service:latest
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
